# Use root/example as user/password credentials
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

# docker network create mynet
# docker run -d --name mongodb --network mynet --restart=always -e MONGO_INITDB_ROOT_USERNAME: root=root -e MONGO_INITDB_ROOT_PASSWORD: example=example mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
# 네트워크는 자동으로 만든다 특별한 지정없으면 

# docker run -d --name mongo-express --network mynet --restart=always -p 8081:8081 \
# -e ME_CONFIG_MONGODB_ADMINUSERNAME=root -e ME_CONFIG_MONGODB_ADMINPASSWORD=example \
# -e ME_CONFIG_MONGODB_URL="mongodb(프로토콜)://root:example@mongodb(서버이름):27017/"
# mongo-express 이미지는 마지막에 쓴다  