# docker run -p 80:80 -v $(pwd)/nginx.conf:/etc/nginx/nginx.conf:ro nginx \
#nginx-debug -g 'daemon off;'
services:
  web:
    image: nginx
    # container_name: my-nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    command: 
      - "nginx-debug" 
      - "-g"
      - "daemon off;"